llm_location:
  # if you state just "gpt-4o" it will take the first, otherwise put azure_openai:gpt-4o
  azure_openai:
    - gpt-4o
    - gpt-4o-mini
  priv_openai:
    - gpt-4o
    - gpt-4o-mini
  dbrx:
    - databricks-dbrx-instruct
    - databricks-meta-llama-3-1-405b-instruct
    - databricks-meta-llama-3-1-70b-instruct
  groq:
    - llama-3.1-8b-instant
    - llama-3.3-70b-versatile
    - llama3-groq-70b-8192-tool-use-preview
    - deepseek-r1-distill-llama-70b
  google_ai_studio:
    - gemini-1.5-pro
    - gemini-exp-1206
    - gemini-2.0-flash
    - gemini-2.0-flash-exp
    - gemini-2.0-flash-thinking-exp-01-21
    - gemini-2.5-pro-exp-03-25
  openrouter:
    - deepseek/deepseek-chat
    - deepseek/deepseek-r1:free
    - cohere/command-r7b-12-2024
    - mistralai/mistral-7b-instruct-v0.2
  deepseek:
    - deepseek-chat
    - deepseek-reasoner
  lingaro:
    - gpt-4o-mini
    - grok-3
