llm_location:
  # if you state just "gpt-4o" it will take the first, otherwise put azure_openai:gpt-4o
  azure_openai:
    - gpt-4o
    - gpt-4o-mini
    - gpt-5
  priv_openai:
    - gpt-4o
    - gpt-4o-mini
  dbrx:
    - databricks-dbrx-instruct
    - databricks-meta-llama-3-1-405b-instruct
    - databricks-meta-llama-3-1-70b-instruct
  groq:
    - llama-3.1-8b-instant
    - llama-3.3-70b-versatile
    - llama3-groq-70b-8192-tool-use-preview
    - deepseek-r1-distill-llama-70b
  google_ai_studio:
    - gemini-flash-latest
    - gemini-2.5-pro
  openrouter:
    - deepseek/deepseek-chat
    - deepseek/deepseek-r1:free
    - cohere/command-r7b-12-2024
    - mistralai/mistral-7b-instruct-v0.2
    - microsoft/phi-3-medium-128k-instruct
  deepseek:
    - deepseek-chat
    - deepseek-reasoner
  lingaro:
    - gpt-4o-mini
    - grok-3
    - deepseek-r1
    - claude-sonnet-4-5
