[project]
name = "talk2data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-core>=1.0.0",
    "langgraph>=1.0.0",
    "openai>=2.5.0",
    "pandas>=2.3.3",
]
